// Generated by gencpp from file go2arm_gazebo/Orientation.msg
// DO NOT EDIT!


#ifndef GO2ARM_GAZEBO_MESSAGE_ORIENTATION_H
#define GO2ARM_GAZEBO_MESSAGE_ORIENTATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace go2arm_gazebo
{
template <class ContainerAllocator>
struct Orientation_
{
  typedef Orientation_<ContainerAllocator> Type;

  Orientation_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  Orientation_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::go2arm_gazebo::Orientation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::go2arm_gazebo::Orientation_<ContainerAllocator> const> ConstPtr;

}; // struct Orientation_

typedef ::go2arm_gazebo::Orientation_<std::allocator<void> > Orientation;

typedef boost::shared_ptr< ::go2arm_gazebo::Orientation > OrientationPtr;
typedef boost::shared_ptr< ::go2arm_gazebo::Orientation const> OrientationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::go2arm_gazebo::Orientation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::go2arm_gazebo::Orientation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::go2arm_gazebo::Orientation_<ContainerAllocator1> & lhs, const ::go2arm_gazebo::Orientation_<ContainerAllocator2> & rhs)
{
  return lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::go2arm_gazebo::Orientation_<ContainerAllocator1> & lhs, const ::go2arm_gazebo::Orientation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace go2arm_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::go2arm_gazebo::Orientation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::go2arm_gazebo::Orientation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::go2arm_gazebo::Orientation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::go2arm_gazebo::Orientation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::go2arm_gazebo::Orientation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::go2arm_gazebo::Orientation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::go2arm_gazebo::Orientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c66f4de7f99199dd8e863fffbef112ad";
  }

  static const char* value(const ::go2arm_gazebo::Orientation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc66f4de7f99199ddULL;
  static const uint64_t static_value2 = 0x8e863fffbef112adULL;
};

template<class ContainerAllocator>
struct DataType< ::go2arm_gazebo::Orientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "go2arm_gazebo/Orientation";
  }

  static const char* value(const ::go2arm_gazebo::Orientation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::go2arm_gazebo::Orientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Orientation.msg\n"
"float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::go2arm_gazebo::Orientation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::go2arm_gazebo::Orientation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Orientation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::go2arm_gazebo::Orientation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::go2arm_gazebo::Orientation_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GO2ARM_GAZEBO_MESSAGE_ORIENTATION_H
