// Generated by gencpp from file go2arm_gazebo/Vector3.msg
// DO NOT EDIT!


#ifndef GO2ARM_GAZEBO_MESSAGE_VECTOR3_H
#define GO2ARM_GAZEBO_MESSAGE_VECTOR3_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace go2arm_gazebo
{
template <class ContainerAllocator>
struct Vector3_
{
  typedef Vector3_<ContainerAllocator> Type;

  Vector3_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  Vector3_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::go2arm_gazebo::Vector3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::go2arm_gazebo::Vector3_<ContainerAllocator> const> ConstPtr;

}; // struct Vector3_

typedef ::go2arm_gazebo::Vector3_<std::allocator<void> > Vector3;

typedef boost::shared_ptr< ::go2arm_gazebo::Vector3 > Vector3Ptr;
typedef boost::shared_ptr< ::go2arm_gazebo::Vector3 const> Vector3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::go2arm_gazebo::Vector3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::go2arm_gazebo::Vector3_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::go2arm_gazebo::Vector3_<ContainerAllocator1> & lhs, const ::go2arm_gazebo::Vector3_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::go2arm_gazebo::Vector3_<ContainerAllocator1> & lhs, const ::go2arm_gazebo::Vector3_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace go2arm_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::go2arm_gazebo::Vector3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::go2arm_gazebo::Vector3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::go2arm_gazebo::Vector3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::go2arm_gazebo::Vector3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::go2arm_gazebo::Vector3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::go2arm_gazebo::Vector3_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::go2arm_gazebo::Vector3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const ::go2arm_gazebo::Vector3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc153912f1453b70ULL;
  static const uint64_t static_value2 = 0x8d221682bc23d9acULL;
};

template<class ContainerAllocator>
struct DataType< ::go2arm_gazebo::Vector3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "go2arm_gazebo/Vector3";
  }

  static const char* value(const ::go2arm_gazebo::Vector3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::go2arm_gazebo::Vector3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Vector3.msg\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::go2arm_gazebo::Vector3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::go2arm_gazebo::Vector3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Vector3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::go2arm_gazebo::Vector3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::go2arm_gazebo::Vector3_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GO2ARM_GAZEBO_MESSAGE_VECTOR3_H
