// Generated by gencpp from file robot_msgs/RobotCommand.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_ROBOTCOMMAND_H
#define ROBOT_MSGS_MESSAGE_ROBOTCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <robot_msgs/MotorCommand.h>

namespace robot_msgs
{
template <class ContainerAllocator>
struct RobotCommand_
{
  typedef RobotCommand_<ContainerAllocator> Type;

  RobotCommand_()
    : motor_command()  {
    }
  RobotCommand_(const ContainerAllocator& _alloc)
    : motor_command()  {
  (void)_alloc;
      motor_command.assign( ::robot_msgs::MotorCommand_<ContainerAllocator> (_alloc));
  }



   typedef boost::array< ::robot_msgs::MotorCommand_<ContainerAllocator> , 32>  _motor_command_type;
  _motor_command_type motor_command;





  typedef boost::shared_ptr< ::robot_msgs::RobotCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::RobotCommand_<ContainerAllocator> const> ConstPtr;

}; // struct RobotCommand_

typedef ::robot_msgs::RobotCommand_<std::allocator<void> > RobotCommand;

typedef boost::shared_ptr< ::robot_msgs::RobotCommand > RobotCommandPtr;
typedef boost::shared_ptr< ::robot_msgs::RobotCommand const> RobotCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::RobotCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::RobotCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msgs::RobotCommand_<ContainerAllocator1> & lhs, const ::robot_msgs::RobotCommand_<ContainerAllocator2> & rhs)
{
  return lhs.motor_command == rhs.motor_command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msgs::RobotCommand_<ContainerAllocator1> & lhs, const ::robot_msgs::RobotCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::RobotCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::RobotCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::RobotCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::RobotCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::RobotCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::RobotCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::RobotCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef1354637f40ee9d0985c79aafa5f40f";
  }

  static const char* value(const ::robot_msgs::RobotCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef1354637f40ee9dULL;
  static const uint64_t static_value2 = 0x0985c79aafa5f40fULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::RobotCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/RobotCommand";
  }

  static const char* value(const ::robot_msgs::RobotCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::RobotCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MotorCommand[32] motor_command\n"
"================================================================================\n"
"MSG: robot_msgs/MotorCommand\n"
"float32 q            # motor target position\n"
"float32 dq           # motor target velocity\n"
"float32 tau          # motor target torque\n"
"float32 kp           # motor spring stiffness coefficient\n"
"float32 kd           # motor damper coefficient\n"
;
  }

  static const char* value(const ::robot_msgs::RobotCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::RobotCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor_command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::RobotCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::RobotCommand_<ContainerAllocator>& v)
  {
    s << indent << "motor_command[]" << std::endl;
    for (size_t i = 0; i < v.motor_command.size(); ++i)
    {
      s << indent << "  motor_command[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::robot_msgs::MotorCommand_<ContainerAllocator> >::stream(s, indent + "    ", v.motor_command[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_ROBOTCOMMAND_H
