# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_msgs/RobotCommand.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import robot_msgs.msg

class RobotCommand(genpy.Message):
  _md5sum = "ef1354637f40ee9d0985c79aafa5f40f"
  _type = "robot_msgs/RobotCommand"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """MotorCommand[32] motor_command
================================================================================
MSG: robot_msgs/MotorCommand
float32 q            # motor target position
float32 dq           # motor target velocity
float32 tau          # motor target torque
float32 kp           # motor spring stiffness coefficient
float32 kd           # motor damper coefficient"""
  __slots__ = ['motor_command']
  _slot_types = ['robot_msgs/MotorCommand[32]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       motor_command

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotCommand, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.motor_command is None:
        self.motor_command = [robot_msgs.msg.MotorCommand() for _ in range(32)]
    else:
      self.motor_command = [robot_msgs.msg.MotorCommand() for _ in range(32)]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      if len(self.motor_command) != 32:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (32, len(self.motor_command), 'self.motor_command')))
      for val1 in self.motor_command:
        _x = val1
        buff.write(_get_struct_5f().pack(_x.q, _x.dq, _x.tau, _x.kp, _x.kd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.motor_command is None:
        self.motor_command = None
      end = 0
      self.motor_command = []
      for i in range(0, 32):
        val1 = robot_msgs.msg.MotorCommand()
        _x = val1
        start = end
        end += 20
        (_x.q, _x.dq, _x.tau, _x.kp, _x.kd,) = _get_struct_5f().unpack(str[start:end])
        self.motor_command.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      if len(self.motor_command) != 32:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (32, len(self.motor_command), 'self.motor_command')))
      for val1 in self.motor_command:
        _x = val1
        buff.write(_get_struct_5f().pack(_x.q, _x.dq, _x.tau, _x.kp, _x.kd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.motor_command is None:
        self.motor_command = None
      end = 0
      self.motor_command = []
      for i in range(0, 32):
        val1 = robot_msgs.msg.MotorCommand()
        _x = val1
        start = end
        end += 20
        (_x.q, _x.dq, _x.tau, _x.kp, _x.kd,) = _get_struct_5f().unpack(str[start:end])
        self.motor_command.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5f = None
def _get_struct_5f():
    global _struct_5f
    if _struct_5f is None:
        _struct_5f = struct.Struct("<5f")
    return _struct_5f
