go2_wx250s_isaacsim:
  model_name: "policy.pt"
  dt: 0.005
  history_length: 10
  mass_ee: 0.4
  mass_base: 6.8
  kp: [40.0, 40.0, 40.0,
       40.0, 40.0, 40.0,
       40.0, 40.0, 40.0,
       40.0, 40.0, 40.0,
       10.0, 10.0, 10.0,
       10.0, 10.0, 10.0]
  kd: [1.0, 1.0, 1.0,
       1.0, 1.0, 1.0,
       1.0, 1.0, 1.0,
       1.0, 1.0, 1.0,
       0.5, 0.5, 0.5,
       0.5, 0.5, 0.5]
  num_of_dofs: 18
  action_scale: 0.25
  default_dof_pos: [-0.1, 0.8, -1.5, 
                     0.1, 0.8, -1.5,
                    -0.1, 1.0, -1.5, 
                     0.1, 1.0, -1.5,  
                     0.0, 0.3,  0.3, 
                     0.0, -0.54, 0.0]
motor_names : ["FR_hip", "FR_thigh", "FR_calf", 
               "FL_hip", "FL_thigh", "FL_calf", 
               "RR_hip", "RR_thigh", "RR_calf",
               "RL_hip", "RL_thigh", "RL_calf", 
               "waist", "shoulder", "elbow", 
               "forearm_roll", "wrist_angle", "wrist_rotate" ]
motor_name_to_idx: {"FR_hip": 0, "FR_thigh": 1, "FR_calf": 2, 
                    "FL_hip": 3, "FL_thigh": 4, "FL_calf": 5, 
                    "RR_hip": 6, "RR_thigh": 7, "RR_calf": 8, 
                    "RL_hip": 9, "RL_thigh": 10, "RL_calf": 11, 
                    "waist": 12, "shoulder": 13, "elbow": 14, 
                    "forearm_roll": 15, "wrist_angle": 16, "wrist_rotate": 17}
foot_names : ["FR_foot", "FL_foot", "RR_foot", "RL_foot"]
foot_name_to_idx: {"FR_foot": 0, "FL_foot": 1, "RR_foot": 2, "RL_foot": 3}
command_ee_x: 0.4
command_ee_z: 0.4
reward_feet_contact_coeff: 0.02
gravity: 9.81
